---
# Tasks specific for RedHat systems

#- name: "RedHat | Set short version name"
#  set_fact:
#      zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
#  tags:
#    - zabbix-agent
#    - init
#
#- name: "RedHat | Use EPEL package name"
#  set_fact:
#      zabbix_agent_package: "zabbix{{ zabbix_short_version }}-agent"
#  when: zabbix_repo == "epel"
#  tags:
#    - zabbix-agent
#    - init



#- name: download file from a file path
#  get_url:
#    url: "https://github.com/Graylog2/collector-sidecar/releases/download/0.0.9/collector-sidecar-0.0.9-1.x86_64.rpm"
#    dest: /tmp/collector-sidecar-0.0.9-1.x86_64.rpm
#    timeout: 30
#  tags:
#    - collector-sidecar
#    - init

- name: "Copy rpm"
  copy: src=collector-sidecar-0.0.9-1.x86_64.rpm
        dest="/tmp/collector-sidecar-0.0.9-1.x86_64.rpm"
        mode=0755
  tags:
    - collector-sidecar
    - init


- name: install the collector-sidecar rpm from a remote repo
  yum: name=/tmp/collector-sidecar-0.0.9-1.x86_64.rpm
  become: yes
  tags:
    - collector-sidecar
    - init

- name: "RedHat | Install basic repo file"
  template: src=collector_sidecar.j2
            dest=/etc/graylog/collector-sidecar/collector_sidecar.yml
            owner=root
            group=root
            mode=0646
  #when: zabbix_repo == "zabbix"
  become: yes
  tags:
    - collector-sidecar
    - init
    - config

- name: Make  directory tree writable
  file:
    path: /etc/graylog/collector-sidecar/
    mode: u=rwX,g=rwX,o=rwX
  become: yes
  tags:
    - collector-sidecar
    - init
    - config
- name: Configure collector_sidecar.yml tags
  lineinfile:
    dest: /etc/graylog/collector-sidecar/collector_sidecar.yml
    regexp: ^#tagsforansible
    line: "{{ item }}"
  with_items:

    - "{{ host_tags }}"

- name: "RedHat | Installing as service"
  command:  graylog-collector-sidecar -service install
  become: yes
  tags:
    - init
    - collector-sidecar

- name: "RedHat | Start as service"
  command:  graylog-collector-sidecar -service start
  become: yes
  tags:
    - init
    - collector-sidecar


